### ISSUE TITLE
Deleting not auto focus backward

### ISSUE THREAD

**Issue by huan415201** [naveenvignesh5/react-native-otp-textinput#37] opened 2023-04-03 16:15 UTC
When I delete, the previous input is not getting focused, so I can't continously delete all the string.

https://user-images.githubusercontent.com/43948939/229567518-f9691b88-3796-4e2b-9a4d-be0f90d65230.mp4

**Comment by iajay** [comment] 2023-05-23 10:33
same happening with me, were you able to solve this?

**Comment by naveenvignesh5** [comment] 2023-07-30 11:07
@huan415201 could you share your code here so that I may take a look ?

**Comment by naveenvignesh5** [comment] 2024-01-13 18:50
Close this issue, as I was not able to reproduce this issue. Also to note that when using physical keyboard for emulator rather than soft keyboard doesn't move cursor back. Tested with soft keyboard as shown in the video indicating the issue. But it worked. Feel free to open the issue and also provide a sample code snippet to so bug could be investigated.

**Closed by naveenvignesh5** 2024-01-13 18:50 UTC
