### ISSUE TITLE
I want button so that i can   clear the input value inside it

### ISSUE THREAD

**Issue by rohanthakran** [naveenvignesh5/react-native-otp-textinput#33] opened 2023-02-03 11:42 UTC
When i am looking at documentation there is a method to clear the value but when I implement is in my code the filed is not clearing

**Comment by mwelwankuta** [comment] 2023-02-10 12:02
it this still the case

**Comment by naveenvignesh5** [comment] 2023-07-30 11:06
@rohanthakran could you paste the snippet here ?

**Comment by naveenvignesh5** [comment] 2024-01-13 18:51
Closing this as the above example will clarify the usage as this is not a bug.

**Closed by naveenvignesh5** 2024-01-13 18:51 UTC
